Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2018-12, with the labels that each got.

#143 2019 May Spec Draft proposal
  spec/20190515-may-upgrade.md
  spec/20190515-reenabled-opcodes.md
  spec/20190515-schnorr.md
Labels: specification

#190 Header redesign translations
  .gitignore
  _config-prod.yml
  _data/languages.yml
  _i18n/de.yml
  _i18n/es.yml
  _i18n/fr.yml
  _i18n/ja.yml
  _i18n/ko.yml
  _i18n/pt-BR.yml
  _i18n/ru.yml
  _i18n/tr.yml
  _i18n/zh-CN.yml
  _i18n/zh-TW.yml
Labels: @Website

#193 Upgrade notice removed
  _includes/home/about.html
  _includes/home/header.html
Labels: @Website

#198 Exchanges cleanup
  _includes/exchanges/exchanges.html
Labels: @Website

#199 Missing nodes re-listed
  _includes/nodes/nodes.html
  img/nodes/copernicus.png
Labels: @Website

#202 Indonesian site enabled
  _config-prod.yml
Labels: @Website

#204 Developer portal temporarily disabled
  _includes/main-menu.html
Labels: @Website

#203 Fixed script path
  _includes/spend/spend.html
Labels: @Website

#208 Update links to Schnorr information
  spec/20190515-schnorr.md
Labels: specification

#209 [spec] fix typo in 2018 Nov upgrade spec
  spec/2018-nov-upgrade.md
Labels: specification

#212 Removed discontinued wallet
  _includes/wallets/wallets.html
Labels: @Website

#215 Blockchain Poker listing restored
  _includes/projects/projects.html
  img/projects/blockchainpoker.png
Labels: @Website

#220 Bitbox SDK link updated
  _includes/projects/projects.html
Labels: @Website

#225 Honest Cash added to project page
  _includes/projects/projects.html
  img/projects/honestcash.jpeg
Labels: @Website

#177 add memopay to Services
  _includes/services/services.html
  img/services/memopay.png
Labels: @Website

#224 Create Avalanche workgroup
  workgroups/wg-avalanche/agenda.md
  workgroups/wg-avalanche/workgroup.md
Labels: workgroups

#229 Beautified URLs
  _includes/accept-bitcoin-cash/accept-bitcoin-cash.html
  _includes/buy-bitcoin-cash/buy-bitcoin-cash.html
  _includes/getting-started/getting-started.html
  _includes/home/about.html
  _includes/home/header.html
  _includes/home/wallets.html
  _includes/main-menu.html
  _includes/spend/spend.html
  _includes/start/start-here.html
  _includes/wallets/wallets.html
  accept-bitcoin-cash.html
  buy-bitcoin-cash.html
  developers.html
  exchanges.html
  faq.html
  get-listed.html
  getting-started.html
  graphics.html
  network-upgrade.html
  nodes.html
  projects.html
  roadmap.html
  services.html
  specs.html
  spend-bitcoin-cash.html
  start-here.html
  tools.html
  wallets.html
  workgroups.html
Labels: @Website

#232 Revised roadmap graphic bubble to adaptive block size
  img/bitcoin-cash-protocol-roadmap.png
Labels: @Website

#234 Added Privacy Policy and Legal Pages
  _includes/footer.html
  _includes/legal/header.html
  _includes/legal/legal.html
  _includes/privacy/header.html
  _includes/privacy/privacy.html
  css/custom.css
  legal.html
  privacy-policy.html
Labels: @Website

#228 [wg] Add another article to Avalanche agenda.md
  workgroups/wg-avalanche/agenda.md
Labels: workgroups
