Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2019-10, with the labels that each got.

#404 [wg] Update Upgrade testnet with new parameters
  workgroups/wg-testing/2019-11-15_upgrade_testnet.md
Labels: workgroups

#408 Remove BCash node
  _includes/nodes/nodes.html
Labels: @Website

#409 Bump Bitcoin ABC version number
  _includes/home/header.html
Labels: @Website

#413 Update our Schnorr to distinguish from new BIP-Schnorr
  spec/2019-05-15-schnorr.md
Labels: specification

#412 Add BCHD to list of Upgrade-ready nodes
  _includes/home/header.html
Labels: @Website

#414 [spec] Remove DRAFT warning from Nov 15 upgrade spec
  spec/2019-11-15-upgrade.md
Labels: specification
