Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2019-05, with the labels that each got.

#337 Add Silico Signing Protocol
  etc/protocols.csv
Labels: specification

#339 Fix typo
  spec/2019-05-15-schnorr.md
Labels: specification

#340 Remove Bitcoin XT
  _includes/nodes/nodes.html
Labels: @Website

#341 Network Upgrade page redirects to MD spec
  _includes/network-upgrade/header.html
  _includes/network-upgrade/message.html
  network-upgrade.html
Labels: @Website

#344 [wg] Add new Upgrade Testnet information
  workgroups/wg-testing/2019-05-15_upgrade_testnet.md
Labels: workgroups

#345 Updated link to point to Electron Cash master repo
  workgroups/wg-testing/2019-05-15_upgrade_testnet.md
Labels: workgroups

#348 reserve cashies protocol in protocols.csv
  etc/protocols.csv
Labels: specification

#346 Updated R-prime spec for minor pedantism.
  spec/2019-05-15-schnorr.md
Labels: specification

#351 Banner set to upgrade complete
  _i18n/en.yml
  _includes/home/header.html
Labels: @Website

#355 [wg] Remove May 15, 2018 Upgrade testnet information.
  workgroups/wg-testing/2019-05-15_upgrade_testnet.md
  workgroups/wg-testing/workgroup.md
Labels: workgroups

#349 spelling and grammar (fr)
  _i18n/fr.yml
Labels: @Website

#360 Donation widget transifexified
  _i18n/en.yml
  _includes/home/about.html
Labels: @Website
