Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2019-11, with the labels that each got.

#415 Update 2019-05-15-upgrade.md
  spec/2019-05-15-upgrade.md
Labels: specification

#416 Update 2019-11-15-schnorrmultisig.md
  spec/2019-11-15-schnorrmultisig.md
Labels: specification

#418 Update title line break
  _includes/developers/header.html
Labels: @Website

#417 Update translations
  _i18n/en.yml
  _i18n/ja.yml
  _i18n/zh-CN.yml
  _i18n/zh-TW.yml
Labels: @Website

#419 [wg] Update Upgrade testnet parameters
  workgroups/wg-testing/2019-11-15_upgrade_testnet.md
Labels: workgroups

#410 Cleanup
  blog/index.html
  learn/bitbox-transaction-utxo.md
  learn/index.html
  tech/index.html
  tech/launch-bitcoincashorg-developer.md
  tech/whitepaper.md
Labels: @Website

#362 [PENDING] Schnorr signatures complete icon
  _includes/roadmap/roadmap.html
Labels: @Website

#422 Set banner to upgrade complete
  _includes/home/header.html
Labels: @Website

#423 Removed fundraiser 'thank you' message
  _includes/fundraise-complete/message.html
  _includes/home/about.html
  fundraise-complete.html
Labels: @Website

#424 Deactivate Upgrade Testnet
  workgroups/wg-testing/2019-11-15_upgrade_testnet.md
Labels: workgroups

#428 Update wallets listings
  _includes/home/wallets.html
  _includes/wallets/wallets.html
Labels: @Website
