Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2019-04, with the labels that each got.

#310 Added string to i18n source
  _i18n/en.yml
  _i18n/en.yml.orig
  _includes/home/roadmap-cta.html
Labels: @Website

#312 Translation update
  _config-prod.yml
  _data/languages.yml
  _i18n/fr.yml
  _i18n/nl.yml
  _i18n/zh-CN.yml
Labels: @Website

#253 Create the blocktime workgroup
  workgroups/wg-blocktime/workgroup.md
Labels: workgroups

#315 Currency formatting update
  js/ticker.js
Labels: @Website

#316 Twitter and Open Graph social cards updated
  _includes/head.html
  img/bitcoincash-twitter.jpg
  img/bitcoincash-twitter.png
Labels: @Website

#320 Translations update
  _i18n/pt-BR.yml
  _i18n/zh-TW.yml
Labels: @Website

#321 Removed Stash wallet
  _includes/wallets/wallets.html
  img/wallets/stashwallet.png
Labels: @Website

#325 Add information for new Activation time
  workgroups/wg-testing/2019-05-15_upgrade_testnet.md
Labels: workgroups

#327 add cashaccounts to protocols.csv
  etc/protocols.csv
Labels: specification

#330 Update protocols.csv
  etc/protocols.csv
Labels: specification

#323 Update segwit recovery specification
  spec/2019-05-15-segwit-recovery.md
Labels: specification

#335 Update "Compatible Implementations" list
  _includes/home/header.html
Labels: @Website

#309 Added LiteBit to the list of exchanges
  _includes/exchanges/exchanges.html
  img/exchanges/litebit.svg
Labels: @Website
