Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2019-08, with the labels that each got.

#387 Update specification for Nov 15th, 2019 upgrade.
  spec/2019-11-15-upgrade.md
Labels: specification

#375 2019 November upgrade: Schnorr OP_CHECKMULTISIG spec
  spec/2019-11-15-schnorrmultisig.md
  spec/2019-11-15-upgrade.md
Labels: specification

#376 2019 November upgrade: MINIMALDATA spec
  spec/2019-11-15-minimaldata.md
  spec/2019-11-15-upgrade.md
Labels: specification

#389 Update coin wallet logo
  _includes/wallets/wallets.html
  img/wallets/coin.png
  img/wallets/coinspace.png
Labels: @Website

#391 Add new Upgrade Testnet information
  workgroups/wg-testing/2019-11-15_upgrade_testnet.md
  workgroups/wg-testing/workgroup.md
Labels: workgroups

#394 [wg] Fix typo in upgrade testnet doc
  workgroups/wg-testing/2019-11-15_upgrade_testnet.md
Labels: workgroups

#395 Broken links fix
  _includes/footer.html
  _includes/home/about.html
  _includes/projects/projects.html
  _includes/spend/spend.html
Labels: @Website

#396 Add Nov 15 2019 Upgrade notice
  _includes/home/header.html
Labels: @Website

#397 Tweak fundraiser complete message
  _includes/fundraise-complete/message.html
  _includes/home/about.html
Labels: @Website
