Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2019-02, with the labels that each got.

#268 [spec] Rename May 2018 Upgrade files
  spec/2019-05-15-reenabled-opcodes.md
  spec/2019-05-15-schnorr.md
  spec/2019-05-15-upgrade.md
Labels: specification

#272 [workgroups] Add more links - Avalanche workgroup
  workgroups/wg-avalanche/agenda.md
Labels: workgroups

#273 update May 2019 draft specification for current track
  spec/2019-05-15-reenabled-opcodes.md
  spec/2019-05-15-segwit-recovery.md
  spec/2019-05-15-upgrade.md
Labels: specification

#274 slant fixes for large desktop, hide slant on giants
  css/graphics.css
Labels: @Website

#276 Internationalization of roadmap content
  _i18n/en.yml
  _includes/roadmap/roadmap.html
Labels: @Website

#275 Roadmap PNG > html/css
  _i18n/en.yml
  _includes/home/about.html
  _includes/home/roadmap-cta.html
  _includes/roadmap/roadmap.html
  css/custom.css
  faq.html
Labels: @Website

#278 Translation update
  _i18n/de.yml
  _i18n/en.yml
  _i18n/fr.yml
  _i18n/ru.yml
Labels: @Website

#279 update segwit recovery specification
  spec/2019-05-15-segwit-recovery.md
Labels: specification

#281 Tighten up Segwit recovery wording.
  spec/2019-05-15-upgrade.md
Labels: specification

#207 2019 May upgrade: add Schnorr opcode specification
  spec/2019-05-15-schnorr.md
Labels: specification

#280 [spec] Remove defunct items from May 2019 Upgrade Spec
  spec/2019-05-15-upgrade.md
Labels: specification

#283 [workgroups] Create testing workgroup
  workgroups/wg-testing/2019-05-15_upgrade_testnet.md
  workgroups/wg-testing/workgroup.md
Labels: workgroups

#284 [spec] Remove "Draft" warnings from May 2019 specs
  spec/2019-05-15-schnorr.md
  spec/2019-05-15-segwit-recovery.md
  spec/2019-05-15-upgrade.md
Labels: specification

#285 [workgroups] Add introduction to testnet document
  workgroups/wg-testing/2019-05-15_upgrade_testnet.md
Labels: workgroups

#286 Navbar update
  _includes/main-menu.html
  css/custom.css
  css/graphics.css
Labels: @Website
