Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2020-04, with the labels that each got.

#430 Add Satoshiwall.cash to projects
  _includes/projects/projects.html
  img/projects/satoshiwall.png
Labels: @Website

#470 [spec] Add a more detailed IFP specification
  spec/2020-05-15-ifp.md
  spec/2020-05-15-upgrade.md
Labels: specification

#448 Add upgrade testnet info for May 15, 2020 upgrade.
  _includes/home/header.html
  workgroups/wg-testing/2019-11-15_upgrade_testnet.md
  workgroups/wg-testing/2020-05-15_upgrade_testnet.md
  workgroups/wg-testing/workgroup.md
Labels: workgroups

#472 Add instructions for upgrade testnet
  workgroups/wg-testing/2020-05-15_upgrade_testnet.md
Labels: workgroups

#463 Registration request for Hashdragon Game Protocol
  etc/protocols.csv
Labels: specification

#466 Revised maps on spend page
  _includes/spend/spend.html
Labels: @Website

#467 Updates to Buy or Earn
  _i18n/en.yml
  _includes/buy-bitcoin-cash/buy-bitcoin-cash.html
  img/micro/readcash.png
  img/micro/tipbitcoin.png
Labels: @Website

#468 Added sideshift to exchanges
  img/exchanges/sideshift.png
Labels: @Website
