Repository bitcoincashorg/bitcoincash.org, pull requests merged in 2020-05, with the labels that each got.

#478 remove DRAFT warning from upgrade specification
  spec/2020-05-15-upgrade.md
Labels: specification

#481 Make ABC version point to latest
  _includes/home/header.html
Labels: @Website

#483 Add BCHD to upgrade compatible implementations
  _includes/home/header.html
  _includes/upgrade/upgrade.html
Labels: @Website

#482 Update ABC version in upgrade page
  _includes/upgrade/upgrade.html
Labels: @Website

#484 Add BCH Unlimited to upgrade compatible implementations
  _includes/home/header.html
  _includes/upgrade/upgrade.html
Labels: @Website

#488 Update testnet instructions post-upgrade
  workgroups/wg-testing/2020-05-15_upgrade_testnet.md
Labels: workgroups

#489 Set website banner to Upgrade Complete
  _includes/home/header.html
  _includes/upgrade/upgrade.html
Labels: @Website

#490 Add link to node upgrade article
  _includes/home/header.html
  _includes/upgrade/upgrade.html
Labels: @Website
